package generator

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
	"time"

	"github.com/el-j/nix-config-collector/internal/core/mapper"
	"github.com/el-j/nix-config-collector/internal/core/models"
)

// Generator implements ports.ConfigGenerator
type Generator struct{}

// New creates a new Generator
func New() *Generator {
	return &Generator{}
}

var darwinConfigTemplate = `# darwin-configuration.nix
# Generated by nix-config-collector on {{ .ScannedAt.Format "2006-01-02 15:04:05" }}
# Hostname: {{ .Hostname }}
{ config, pkgs, lib, ... }:
{
  # Nix configuration
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.trusted-users = [ "root" "@admin" ];

  # System packages (mapped from Homebrew formulae)
  environment.systemPackages = with pkgs; [
    {{- range .NixPackages }}
    {{ .NixName }}
    {{- end }}
  ];

  # Homebrew configuration
  homebrew = {
    enable = true;
    onActivation = {
      autoUpdate = true;
      cleanup = "zap";
    };
    {{- if .BrewFormulae }}
    brews = [
      {{- range .BrewFormulae }}
      "{{ .Name }}"
      {{- end }}
    ];
    {{- end }}
    {{- if .BrewCasks }}
    casks = [
      {{- range .BrewCasks }}
      "{{ .Name }}"
      {{- end }}
    ];
    {{- end }}
    {{- if .MASApps }}
    masApps = {
      {{- range .MASApps }}
      "{{ .Name }}" = 0; # TODO: add App Store ID
      {{- end }}
    };
    {{- end }}
  };

  # System preferences
  system.defaults = {
    dock = {
      {{- range .DockPrefs }}
      {{ .Key }} = {{ .NixValue }};
      {{- end }}
    };
    finder = {
      {{- range .FinderPrefs }}
      {{ .Key }} = {{ .NixValue }};
      {{- end }}
    };
    NSGlobalDomain = {
      {{- range .GlobalPrefs }}
      {{ .Key }} = {{ .NixValue }};
      {{- end }}
    };
  };

  # macOS system settings
  system.stateVersion = 4;
  services.nix-daemon.enable = true;
  programs.nix-index.enable = true;
}
`

var homeConfigTemplate = `# home.nix
# Generated by nix-config-collector on {{ .ScannedAt.Format "2006-01-02 15:04:05" }}
{ config, pkgs, lib, ... }:
{
  home.username = "{{ .Username }}";
  home.homeDirectory = "/Users/{{ .Username }}";
  home.stateVersion = "23.11";

  # User packages
  home.packages = with pkgs; [
    {{- range .NixPackages }}
    {{ .NixName }}
    {{- end }}
  ];

  {{- if .IsZsh }}
  programs.zsh = {
    enable = true;
  };
  {{- end }}

  {{- if .IsBash }}
  programs.bash = {
    enable = true;
  };
  {{- end }}

  {{- if .IsFish }}
  programs.fish = {
    enable = true;
  };
  {{- end }}

  {{- if .GitConfig }}
  programs.git = {
    enable = true;
    {{- if .GitUserName }}
    userName = "{{ .GitUserName }}";
    {{- end }}
    {{- if .GitUserEmail }}
    userEmail = "{{ .GitUserEmail }}";
    {{- end }}
  };
  {{- end }}

  programs.home-manager.enable = true;
}
`

var flakeConfigTemplate = `# flake.nix
# Generated by nix-config-collector on {{ .ScannedAt.Format "2006-01-02 15:04:05" }}
{{- $dollar := "$" }}
{
  description = "{{ .Hostname }} nix-darwin configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin = {
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@{ self, nix-darwin, nixpkgs, home-manager, ... }:
  let
    system = "aarch64-darwin"; # or "x86_64-darwin" for Intel Macs
    pkgs = nixpkgs.legacyPackages.{{ $dollar }}{system};
  in
  {
    darwinConfigurations."{{ .Hostname }}" = nix-darwin.lib.darwinSystem {
      inherit system;
      modules = [
        ./darwin-configuration.nix
        home-manager.darwinModules.home-manager
        {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.users.{{ .Username }} = import ./home.nix;
        }
      ];
    };
  };
}
`

type prefEntry struct {
	Key      string
	NixValue string
}

type darwinTemplateData struct {
	ScannedAt    time.Time
	Hostname     string
	NixPackages  []models.Package
	BrewFormulae []models.Package
	BrewCasks    []models.Package
	MASApps      []models.Package
	DockPrefs    []prefEntry
	FinderPrefs  []prefEntry
	GlobalPrefs  []prefEntry
}

type homeTemplateData struct {
	ScannedAt    time.Time
	Username     string
	NixPackages  []models.Package
	IsZsh        bool
	IsBash       bool
	IsFish       bool
	GitConfig    bool
	GitUserName  string
	GitUserEmail string
}

type flakeTemplateData struct {
	ScannedAt time.Time
	Hostname  string
	Username  string
}

// GenerateDarwinConfig generates darwin-configuration.nix
func (g *Generator) GenerateDarwinConfig(scan models.SystemScan) (string, error) {
	nixPkgs, brewFormulae, brewCasks, masApps := mapper.SplitByDestination(scan.Packages)

	data := darwinTemplateData{
		ScannedAt:    scan.ScannedAt,
		Hostname:     scan.Hostname,
		NixPackages:  nixPkgs,
		BrewFormulae: brewFormulae,
		BrewCasks:    brewCasks,
		MASApps:      masApps,
	}

	for _, pref := range scan.Preferences {
		entry := prefEntry{
			Key:      pref.Key,
			NixValue: toNixValue(fmt.Sprintf("%v", pref.Value)),
		}
		switch pref.Domain {
		case "com.apple.dock":
			data.DockPrefs = append(data.DockPrefs, entry)
		case "com.apple.finder":
			data.FinderPrefs = append(data.FinderPrefs, entry)
		case "NSGlobalDomain":
			data.GlobalPrefs = append(data.GlobalPrefs, entry)
		}
	}

	return renderTemplate("darwin", darwinConfigTemplate, data)
}

// GenerateHomeConfig generates home.nix
func (g *Generator) GenerateHomeConfig(scan models.SystemScan) (string, error) {
	nixPkgs, _, _, _ := mapper.SplitByDestination(scan.Packages)

	data := homeTemplateData{
		ScannedAt:   scan.ScannedAt,
		Username:    extractUsername(),
		NixPackages: nixPkgs,
		IsZsh:       strings.Contains(scan.ShellConfig.Shell, "zsh"),
		IsBash:      strings.Contains(scan.ShellConfig.Shell, "bash"),
		IsFish:      strings.Contains(scan.ShellConfig.Shell, "fish"),
	}

	for _, df := range scan.Dotfiles {
		if strings.HasSuffix(df.Path, ".gitconfig") {
			data.GitConfig = true
			data.GitUserName = extractGitValue(df.Content, "name")
			data.GitUserEmail = extractGitValue(df.Content, "email")
		}
	}

	return renderTemplate("home", homeConfigTemplate, data)
}

// GenerateFlakeConfig generates flake.nix
func (g *Generator) GenerateFlakeConfig(scan models.SystemScan) (string, error) {
	data := flakeTemplateData{
		ScannedAt: scan.ScannedAt,
		Hostname:  scan.Hostname,
		Username:  extractUsername(),
	}
	return renderTemplate("flake", flakeConfigTemplate, data)
}

func renderTemplate(name, tmplStr string, data interface{}) (string, error) {
	tmpl, err := template.New(name).Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("parsing template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template %s: %w", name, err)
	}
	return buf.String(), nil
}

func toNixValue(v string) string {
	v = strings.TrimSpace(v)
	switch v {
	case "1", "true", "TRUE":
		return "true"
	case "0", "false", "FALSE":
		return "false"
	}
	if _, err := fmt.Sscanf(v, "%d", new(int)); err == nil {
		return v
	}
	return fmt.Sprintf("%q", v)
}

func extractUsername() string {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		if user := os.Getenv("USER"); user != "" {
			return user
		}
		return "user"
	}
	parts := strings.Split(homeDir, "/")
	if len(parts) >= 3 && parts[1] == "Users" {
		return parts[2]
	}
	if user := os.Getenv("USER"); user != "" {
		return user
	}
	return "user"
}

func extractGitValue(content, key string) string {
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, key+" = ") || strings.HasPrefix(line, key+"=") {
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				return strings.TrimSpace(parts[1])
			}
		}
	}
	return ""
}
