// This file is auto-generated by Wails when you run `wails build`.
// For development, it provides type hints and stubs.

export function Scan() {
  return window['go']['gui']['App']['Scan']()
}

export function Generate(outputDir) {
  return window['go']['gui']['App']['Generate'](outputDir)
}

export function Preview() {
  return window['go']['gui']['App']['Preview']()
}
